/* eslint-disable */
// source: proto/mdiningapi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var proto_dininghalls_pb = require('../proto/dininghalls_pb.js');
goog.object.extend(proto, proto_dininghalls_pb);
var proto_items_pb = require('../proto/items_pb.js');
goog.object.extend(proto, proto_items_pb);
var proto_filterableentries_pb = require('../proto/filterableentries_pb.js');
goog.object.extend(proto, proto_filterableentries_pb);
var proto_menu_pb = require('../proto/menu_pb.js');
goog.object.extend(proto, proto_menu_pb);
goog.exportSymbol('proto.mdiningapi.DiningHallGroup', null, global);
goog.exportSymbol('proto.mdiningapi.GetDiningHallsReply', null, global);
goog.exportSymbol('proto.mdiningapi.GetMenuBaseReply', null, global);
goog.exportSymbol('proto.mdiningapi.GetMenuDetailsReply', null, global);
goog.exportSymbol('proto.mdiningapi.MenuBase', null, global);
goog.exportSymbol('proto.mdiningapi.MenuDetail', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mdiningapi.GetDiningHallsReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mdiningapi.GetDiningHallsReply.repeatedFields_, null);
};
goog.inherits(proto.mdiningapi.GetDiningHallsReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mdiningapi.GetDiningHallsReply.displayName = 'proto.mdiningapi.GetDiningHallsReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mdiningapi.DiningHallGroup = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mdiningapi.DiningHallGroup.repeatedFields_, null);
};
goog.inherits(proto.mdiningapi.DiningHallGroup, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mdiningapi.DiningHallGroup.displayName = 'proto.mdiningapi.DiningHallGroup';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mdiningapi.GetMenuBaseReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mdiningapi.GetMenuBaseReply.repeatedFields_, null);
};
goog.inherits(proto.mdiningapi.GetMenuBaseReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mdiningapi.GetMenuBaseReply.displayName = 'proto.mdiningapi.GetMenuBaseReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mdiningapi.MenuBase = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mdiningapi.MenuBase, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mdiningapi.MenuBase.displayName = 'proto.mdiningapi.MenuBase';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mdiningapi.GetMenuDetailsReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mdiningapi.GetMenuDetailsReply.repeatedFields_, null);
};
goog.inherits(proto.mdiningapi.GetMenuDetailsReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mdiningapi.GetMenuDetailsReply.displayName = 'proto.mdiningapi.GetMenuDetailsReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mdiningapi.MenuDetail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mdiningapi.MenuDetail.repeatedFields_, null);
};
goog.inherits(proto.mdiningapi.MenuDetail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mdiningapi.MenuDetail.displayName = 'proto.mdiningapi.MenuDetail';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mdiningapi.GetDiningHallsReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mdiningapi.GetDiningHallsReply.prototype.toObject = function(opt_includeInstance) {
  return proto.mdiningapi.GetDiningHallsReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mdiningapi.GetDiningHallsReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mdiningapi.GetDiningHallsReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    dininghallgroupList: jspb.Message.toObjectList(msg.getDininghallgroupList(),
    proto.mdiningapi.DiningHallGroup.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mdiningapi.GetDiningHallsReply}
 */
proto.mdiningapi.GetDiningHallsReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mdiningapi.GetDiningHallsReply;
  return proto.mdiningapi.GetDiningHallsReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mdiningapi.GetDiningHallsReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mdiningapi.GetDiningHallsReply}
 */
proto.mdiningapi.GetDiningHallsReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.mdiningapi.DiningHallGroup;
      reader.readMessage(value,proto.mdiningapi.DiningHallGroup.deserializeBinaryFromReader);
      msg.addDininghallgroup(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mdiningapi.GetDiningHallsReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mdiningapi.GetDiningHallsReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mdiningapi.GetDiningHallsReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mdiningapi.GetDiningHallsReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDininghallgroupList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.mdiningapi.DiningHallGroup.serializeBinaryToWriter
    );
  }
};


/**
 * repeated DiningHallGroup diningHallGroup = 1;
 * @return {!Array<!proto.mdiningapi.DiningHallGroup>}
 */
proto.mdiningapi.GetDiningHallsReply.prototype.getDininghallgroupList = function() {
  return /** @type{!Array<!proto.mdiningapi.DiningHallGroup>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mdiningapi.DiningHallGroup, 1));
};


/**
 * @param {!Array<!proto.mdiningapi.DiningHallGroup>} value
 * @return {!proto.mdiningapi.GetDiningHallsReply} returns this
*/
proto.mdiningapi.GetDiningHallsReply.prototype.setDininghallgroupList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.mdiningapi.DiningHallGroup=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mdiningapi.DiningHallGroup}
 */
proto.mdiningapi.GetDiningHallsReply.prototype.addDininghallgroup = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.mdiningapi.DiningHallGroup, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mdiningapi.GetDiningHallsReply} returns this
 */
proto.mdiningapi.GetDiningHallsReply.prototype.clearDininghallgroupList = function() {
  return this.setDininghallgroupList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mdiningapi.DiningHallGroup.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mdiningapi.DiningHallGroup.prototype.toObject = function(opt_includeInstance) {
  return proto.mdiningapi.DiningHallGroup.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mdiningapi.DiningHallGroup} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mdiningapi.DiningHallGroup.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    dininghallList: jspb.Message.toObjectList(msg.getDininghallList(),
    proto_dininghalls_pb.DiningHall.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mdiningapi.DiningHallGroup}
 */
proto.mdiningapi.DiningHallGroup.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mdiningapi.DiningHallGroup;
  return proto.mdiningapi.DiningHallGroup.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mdiningapi.DiningHallGroup} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mdiningapi.DiningHallGroup}
 */
proto.mdiningapi.DiningHallGroup.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new proto_dininghalls_pb.DiningHall;
      reader.readMessage(value,proto_dininghalls_pb.DiningHall.deserializeBinaryFromReader);
      msg.addDininghall(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mdiningapi.DiningHallGroup.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mdiningapi.DiningHallGroup.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mdiningapi.DiningHallGroup} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mdiningapi.DiningHallGroup.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDininghallList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto_dininghalls_pb.DiningHall.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.mdiningapi.DiningHallGroup.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.mdiningapi.DiningHallGroup} returns this
 */
proto.mdiningapi.DiningHallGroup.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated mdining.DiningHall diningHall = 2;
 * @return {!Array<!proto.mdining.DiningHall>}
 */
proto.mdiningapi.DiningHallGroup.prototype.getDininghallList = function() {
  return /** @type{!Array<!proto.mdining.DiningHall>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_dininghalls_pb.DiningHall, 2));
};


/**
 * @param {!Array<!proto.mdining.DiningHall>} value
 * @return {!proto.mdiningapi.DiningHallGroup} returns this
*/
proto.mdiningapi.DiningHallGroup.prototype.setDininghallList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.mdining.DiningHall=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mdining.DiningHall}
 */
proto.mdiningapi.DiningHallGroup.prototype.addDininghall = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.mdining.DiningHall, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mdiningapi.DiningHallGroup} returns this
 */
proto.mdiningapi.DiningHallGroup.prototype.clearDininghallList = function() {
  return this.setDininghallList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mdiningapi.GetMenuBaseReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mdiningapi.GetMenuBaseReply.prototype.toObject = function(opt_includeInstance) {
  return proto.mdiningapi.GetMenuBaseReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mdiningapi.GetMenuBaseReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mdiningapi.GetMenuBaseReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    menuList: jspb.Message.toObjectList(msg.getMenuList(),
    proto.mdiningapi.MenuBase.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mdiningapi.GetMenuBaseReply}
 */
proto.mdiningapi.GetMenuBaseReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mdiningapi.GetMenuBaseReply;
  return proto.mdiningapi.GetMenuBaseReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mdiningapi.GetMenuBaseReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mdiningapi.GetMenuBaseReply}
 */
proto.mdiningapi.GetMenuBaseReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.mdiningapi.MenuBase;
      reader.readMessage(value,proto.mdiningapi.MenuBase.deserializeBinaryFromReader);
      msg.addMenu(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mdiningapi.GetMenuBaseReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mdiningapi.GetMenuBaseReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mdiningapi.GetMenuBaseReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mdiningapi.GetMenuBaseReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMenuList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.mdiningapi.MenuBase.serializeBinaryToWriter
    );
  }
};


/**
 * repeated MenuBase menu = 1;
 * @return {!Array<!proto.mdiningapi.MenuBase>}
 */
proto.mdiningapi.GetMenuBaseReply.prototype.getMenuList = function() {
  return /** @type{!Array<!proto.mdiningapi.MenuBase>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mdiningapi.MenuBase, 1));
};


/**
 * @param {!Array<!proto.mdiningapi.MenuBase>} value
 * @return {!proto.mdiningapi.GetMenuBaseReply} returns this
*/
proto.mdiningapi.GetMenuBaseReply.prototype.setMenuList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.mdiningapi.MenuBase=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mdiningapi.MenuBase}
 */
proto.mdiningapi.GetMenuBaseReply.prototype.addMenu = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.mdiningapi.MenuBase, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mdiningapi.GetMenuBaseReply} returns this
 */
proto.mdiningapi.GetMenuBaseReply.prototype.clearMenuList = function() {
  return this.setMenuList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mdiningapi.MenuBase.prototype.toObject = function(opt_includeInstance) {
  return proto.mdiningapi.MenuBase.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mdiningapi.MenuBase} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mdiningapi.MenuBase.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    date: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    formatteddate: jspb.Message.getFieldWithDefault(msg, 4, ""),
    ratingcount: jspb.Message.getFieldWithDefault(msg, 5, 0),
    ratingscore: jspb.Message.getFieldWithDefault(msg, 6, 0),
    hascategories: jspb.Message.getBooleanFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mdiningapi.MenuBase}
 */
proto.mdiningapi.MenuBase.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mdiningapi.MenuBase;
  return proto.mdiningapi.MenuBase.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mdiningapi.MenuBase} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mdiningapi.MenuBase}
 */
proto.mdiningapi.MenuBase.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDate(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFormatteddate(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRatingcount(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRatingscore(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHascategories(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mdiningapi.MenuBase.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mdiningapi.MenuBase.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mdiningapi.MenuBase} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mdiningapi.MenuBase.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDate();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFormatteddate();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getRatingcount();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getRatingscore();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getHascategories();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.mdiningapi.MenuBase.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.mdiningapi.MenuBase} returns this
 */
proto.mdiningapi.MenuBase.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string date = 2;
 * @return {string}
 */
proto.mdiningapi.MenuBase.prototype.getDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.mdiningapi.MenuBase} returns this
 */
proto.mdiningapi.MenuBase.prototype.setDate = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.mdiningapi.MenuBase.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.mdiningapi.MenuBase} returns this
 */
proto.mdiningapi.MenuBase.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string formattedDate = 4;
 * @return {string}
 */
proto.mdiningapi.MenuBase.prototype.getFormatteddate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.mdiningapi.MenuBase} returns this
 */
proto.mdiningapi.MenuBase.prototype.setFormatteddate = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 ratingCount = 5;
 * @return {number}
 */
proto.mdiningapi.MenuBase.prototype.getRatingcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.mdiningapi.MenuBase} returns this
 */
proto.mdiningapi.MenuBase.prototype.setRatingcount = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 ratingScore = 6;
 * @return {number}
 */
proto.mdiningapi.MenuBase.prototype.getRatingscore = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.mdiningapi.MenuBase} returns this
 */
proto.mdiningapi.MenuBase.prototype.setRatingscore = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional bool hasCategories = 7;
 * @return {boolean}
 */
proto.mdiningapi.MenuBase.prototype.getHascategories = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.mdiningapi.MenuBase} returns this
 */
proto.mdiningapi.MenuBase.prototype.setHascategories = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mdiningapi.GetMenuDetailsReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mdiningapi.GetMenuDetailsReply.prototype.toObject = function(opt_includeInstance) {
  return proto.mdiningapi.GetMenuDetailsReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mdiningapi.GetMenuDetailsReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mdiningapi.GetMenuDetailsReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    menuList: jspb.Message.toObjectList(msg.getMenuList(),
    proto.mdiningapi.MenuDetail.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mdiningapi.GetMenuDetailsReply}
 */
proto.mdiningapi.GetMenuDetailsReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mdiningapi.GetMenuDetailsReply;
  return proto.mdiningapi.GetMenuDetailsReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mdiningapi.GetMenuDetailsReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mdiningapi.GetMenuDetailsReply}
 */
proto.mdiningapi.GetMenuDetailsReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.mdiningapi.MenuDetail;
      reader.readMessage(value,proto.mdiningapi.MenuDetail.deserializeBinaryFromReader);
      msg.addMenu(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mdiningapi.GetMenuDetailsReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mdiningapi.GetMenuDetailsReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mdiningapi.GetMenuDetailsReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mdiningapi.GetMenuDetailsReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMenuList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.mdiningapi.MenuDetail.serializeBinaryToWriter
    );
  }
};


/**
 * repeated MenuDetail menu = 1;
 * @return {!Array<!proto.mdiningapi.MenuDetail>}
 */
proto.mdiningapi.GetMenuDetailsReply.prototype.getMenuList = function() {
  return /** @type{!Array<!proto.mdiningapi.MenuDetail>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mdiningapi.MenuDetail, 1));
};


/**
 * @param {!Array<!proto.mdiningapi.MenuDetail>} value
 * @return {!proto.mdiningapi.GetMenuDetailsReply} returns this
*/
proto.mdiningapi.GetMenuDetailsReply.prototype.setMenuList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.mdiningapi.MenuDetail=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mdiningapi.MenuDetail}
 */
proto.mdiningapi.GetMenuDetailsReply.prototype.addMenu = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.mdiningapi.MenuDetail, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mdiningapi.GetMenuDetailsReply} returns this
 */
proto.mdiningapi.GetMenuDetailsReply.prototype.clearMenuList = function() {
  return this.setMenuList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mdiningapi.MenuDetail.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mdiningapi.MenuDetail.prototype.toObject = function(opt_includeInstance) {
  return proto.mdiningapi.MenuDetail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mdiningapi.MenuDetail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mdiningapi.MenuDetail.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    date: jspb.Message.getFieldWithDefault(msg, 2, ""),
    formatteddate: jspb.Message.getFieldWithDefault(msg, 3, ""),
    ratingcount: jspb.Message.getFieldWithDefault(msg, 4, 0),
    ratingscore: jspb.Message.getFieldWithDefault(msg, 5, 0),
    hascategories: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    description: jspb.Message.getFieldWithDefault(msg, 7, ""),
    categoryList: jspb.Message.toObjectList(msg.getCategoryList(),
    proto_menu_pb.Category.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mdiningapi.MenuDetail}
 */
proto.mdiningapi.MenuDetail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mdiningapi.MenuDetail;
  return proto.mdiningapi.MenuDetail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mdiningapi.MenuDetail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mdiningapi.MenuDetail}
 */
proto.mdiningapi.MenuDetail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDate(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFormatteddate(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRatingcount(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRatingscore(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHascategories(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 8:
      var value = new proto_menu_pb.Category;
      reader.readMessage(value,proto_menu_pb.Category.deserializeBinaryFromReader);
      msg.addCategory(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mdiningapi.MenuDetail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mdiningapi.MenuDetail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mdiningapi.MenuDetail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mdiningapi.MenuDetail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDate();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFormatteddate();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRatingcount();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getRatingscore();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getHascategories();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getCategoryList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto_menu_pb.Category.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.mdiningapi.MenuDetail.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.mdiningapi.MenuDetail} returns this
 */
proto.mdiningapi.MenuDetail.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string date = 2;
 * @return {string}
 */
proto.mdiningapi.MenuDetail.prototype.getDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.mdiningapi.MenuDetail} returns this
 */
proto.mdiningapi.MenuDetail.prototype.setDate = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string formattedDate = 3;
 * @return {string}
 */
proto.mdiningapi.MenuDetail.prototype.getFormatteddate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.mdiningapi.MenuDetail} returns this
 */
proto.mdiningapi.MenuDetail.prototype.setFormatteddate = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 ratingCount = 4;
 * @return {number}
 */
proto.mdiningapi.MenuDetail.prototype.getRatingcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.mdiningapi.MenuDetail} returns this
 */
proto.mdiningapi.MenuDetail.prototype.setRatingcount = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 ratingScore = 5;
 * @return {number}
 */
proto.mdiningapi.MenuDetail.prototype.getRatingscore = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.mdiningapi.MenuDetail} returns this
 */
proto.mdiningapi.MenuDetail.prototype.setRatingscore = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool hasCategories = 6;
 * @return {boolean}
 */
proto.mdiningapi.MenuDetail.prototype.getHascategories = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.mdiningapi.MenuDetail} returns this
 */
proto.mdiningapi.MenuDetail.prototype.setHascategories = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional string description = 7;
 * @return {string}
 */
proto.mdiningapi.MenuDetail.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.mdiningapi.MenuDetail} returns this
 */
proto.mdiningapi.MenuDetail.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * repeated mdining.Category category = 8;
 * @return {!Array<!proto.mdining.Category>}
 */
proto.mdiningapi.MenuDetail.prototype.getCategoryList = function() {
  return /** @type{!Array<!proto.mdining.Category>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_menu_pb.Category, 8));
};


/**
 * @param {!Array<!proto.mdining.Category>} value
 * @return {!proto.mdiningapi.MenuDetail} returns this
*/
proto.mdiningapi.MenuDetail.prototype.setCategoryList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.mdining.Category=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mdining.Category}
 */
proto.mdiningapi.MenuDetail.prototype.addCategory = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.mdining.Category, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mdiningapi.MenuDetail} returns this
 */
proto.mdiningapi.MenuDetail.prototype.clearCategoryList = function() {
  return this.setCategoryList([]);
};


goog.object.extend(exports, proto.mdiningapi);
